export const ROUTES = {
  home: "/",
  about: "/gioi-thieu",
  services: "/dich-vu",
  serviceDetail: (slug: string) => `/dich-vu/${slug}`,
  projects: "/du-an",
  projectDetail: (slug: string) => `/du-an/${slug}`,
  courses: "/khoa-hoc",
  courseDetail: (slug: string) => `/khoa-hoc/${slug}`,
  blog: "/blog",
  blogDetail: (slug: string) => `/blog/${slug}`,
  technical: "/chuyen-mon",
  technicalDetail: (slug: string) => `/chuyen-mon/${slug}`,
  news: "/tin-tuc",
  newsDetail: (slug: string) => `/tin-tuc/${slug}`,
  legal: "/phap-ly",
  legalDetail: (slug: string) => `/phap-ly/${slug}`,
  contact: "/lien-he",
  bimViewer: "/bim-viewer",
} as const;
