"use client";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";

export default function AdminLogin() {
  const router=useRouter(); const params=useSearchParams(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!response.ok){const body=await response.json().catch(()=>null) as {message?:string}|null;throw new Error(body?.message??'Đăng nhập thất bại');}const next=params.get('next');router.replace(next?.startsWith('/admin')?next:'/admin');router.refresh();}catch(e){setError(e instanceof Error?e.message:'Đăng nhập thất bại');}finally{setBusy(false)}}
  return <main className="grid min-h-screen place-items-center bg-[radial-gradient(circle_at_18%_16%,rgba(9,167,165,.26),transparent_30%),#063f46] p-4 sm:p-6"><form onSubmit={submit} className="grid min-w-0 w-[calc(100vw-32px)] max-w-[440px] gap-[18px] rounded-md border border-white/10 bg-white p-6 shadow-2xl sm:w-full sm:p-8"><div className="flex flex-col border-b border-[#dbe7e5] pb-5"><span className="text-3xl font-bold text-[#163b3a]">BIM<span className="text-[#09a7a5]">4C</span></span><small className="mt-1 text-micro font-semibold tracking-[.18em] text-[#667775]">ADMIN CMS</small></div><h1 className="mb-0 text-2xl font-semibold text-[#163b3a]">Đăng nhập quản trị</h1><label className="grid min-w-0 gap-1.5 text-label font-medium text-[#667775]">Email<input className="min-h-11 min-w-0 w-full rounded border border-[#dbe7e5] px-3 outline-none transition focus:border-[#09a7a5] focus:ring-2 focus:ring-[#09a7a5]/10" autoComplete="username" type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="grid min-w-0 gap-1.5 text-label font-medium text-[#667775]">Mật khẩu<input className="min-h-11 min-w-0 w-full rounded border border-[#dbe7e5] px-3 outline-none transition focus:border-[#09a7a5] focus:ring-2 focus:ring-[#09a7a5]/10" autoComplete="current-password" type="password" required minLength={10} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="m-0 rounded bg-red-50 px-3 py-2.5 text-xs text-red-700">{error}</p>}<button className="inline-flex min-h-11 items-center justify-center rounded bg-[#087f7d] px-5 text-label font-semibold text-white transition hover:bg-[#087f7d] disabled:cursor-wait disabled:opacity-50" disabled={busy} type="submit">{busy?'Đang đăng nhập…':'Đăng nhập'}</button></form></main>;
}
