import Link from "next/link";
import { ROUTES } from "@/constants/routes";
import { NewsletterForm } from "@/features/contact/components/NewsletterForm";

const information = [{ label: "Giới thiệu", href: ROUTES.about }, { label: "Dịch vụ", href: ROUTES.services }, { label: "Dự án", href: ROUTES.projects }, { label: "Khóa học", href: ROUTES.courses }, { label: "Blog", href: ROUTES.blog }];
const legal = [{ label: "Chính sách bảo mật", href: ROUTES.legalDetail("chinh-sach-bao-mat") }, { label: "Điều khoản sử dụng", href: ROUTES.legalDetail("dieu-khoan-su-dung") }, { label: "Bảo vệ dữ liệu cá nhân", href: ROUTES.legalDetail("bao-ve-du-lieu-ca-nhan") }];
const heading = "mb-5 text-[16px] font-semibold uppercase tracking-[.04em] text-white";
const footerLink = "text-[14px] font-medium text-white/70 transition-colors hover:text-white hover:underline hover:underline-offset-4";

export function Footer() {
  return <footer className="w-full bg-[#063f46] text-white" id="contact"><div className="mx-auto grid w-[calc(100%_-_32px)] max-w-[1400px] grid-cols-1 gap-12 py-16 md:w-[calc(100%_-_64px)] md:grid-cols-2 md:py-20 lg:grid-cols-[1.7fr_.65fr_.75fr_1.25fr] lg:gap-10"><div><h2 className="mb-5 text-2xl font-semibold">BIM4C CONSTRUCTION</h2><p className="mb-7 max-w-[500px] text-[16px] leading-6 text-white/80">Kiến tạo nền tảng vững chắc cho tương lai thông qua công nghệ BIM và quy trình quản lý xây dựng hiện đại.</p><div className="grid gap-3"><div className="flex flex-col"><strong className="text-xs uppercase">Văn phòng miền Bắc</strong><span className="text-xs text-white/70">Hà Nội, Việt Nam</span></div><div className="flex flex-col"><strong className="text-xs uppercase">Văn phòng miền Nam</strong><span className="text-xs text-white/70">TP. Hồ Chí Minh, Việt Nam</span></div><a className="text-xs text-white/70 hover:text-white" href={ROUTES.contactEmail}>info@bim4c.vn</a></div></div><div><h3 className={heading}>Thông tin</h3><ul className="m-0 list-none p-0">{information.map((item) => <li className="mb-2.5" key={item.label}><Link className={footerLink} href={item.href}>{item.label}</Link></li>)}</ul></div><div><h3 className={heading}><Link href={ROUTES.legal}>Pháp lý</Link></h3><ul className="m-0 list-none p-0">{legal.map((item) => <li className="mb-2.5" key={item.href}><Link className={footerLink} href={item.href}>{item.label}</Link></li>)}</ul></div><div><h3 className={heading}>Đăng ký nhận tin</h3><p className="mb-[18px] text-xs text-white/70">Cập nhật dự án, khóa học và kiến thức BIM mới nhất.</p><NewsletterForm /></div></div><div className="border-t border-white/20 p-5 text-center text-xs text-white/70">© 2026 BIM4C CONSTRUCTION. ALL RIGHTS RESERVED.</div></footer>;
}
