import type { Metadata } from "next";
import Image from "next/image";
import { PageHero } from "@/components/shared/PageHero";
import { ContactBand } from "@/components/shared/ContactBand";
import { Leadership } from "@/components/sections/Leadership";
import { companyStats } from "@/constants/site-content";
export const metadata:Metadata={title:"Giới thiệu | BIM4C",description:"Tìm hiểu về BIM4C, tầm nhìn và năng lực xây dựng số."};
const milestones=[{year:"2004",title:"Khởi tạo nền tảng",text:"Hình thành đội ngũ với định hướng ứng dụng công nghệ vào quản lý xây dựng."},{year:"2012",title:"Mở rộng năng lực",text:"Phát triển hoạt động tư vấn, thiết kế và phối hợp kỹ thuật đa bộ môn."},{year:"2018",title:"Chuyển đổi số",text:"Chuẩn hóa quy trình BIM và môi trường dữ liệu chung cho các dự án."},{year:"2026",title:"Kiến tạo tương lai",text:"Hướng đến hệ sinh thái xây dựng số hiệu quả, minh bạch và bền vững."}];
export default function AboutPage(){return <main className="about-page"><PageHero eyebrow="VỀ BIM4C" title="Kiến tạo giá trị bền vững" description="Tiên phong ứng dụng công nghệ và quy trình quản trị hiện đại trong ngành xây dựng Việt Nam." image="/images/about.jpg"/>
  <section className="about-overview"><div className="about-overview-media"><Image src="/images/hero.jpg" alt="Công trình tiêu biểu BIM4C" fill sizes="(max-width: 900px) 100vw, 50vw"/><div><strong>20+</strong><span>Năm kiến tạo<br/>giá trị</span></div></div><div className="about-overview-copy"><p className="eyebrow">TỔNG QUAN BIM4C</p><h2>Công nghệ là nền tảng.<br/><em>Con người tạo khác biệt.</em></h2><p>BIM4C quy tụ đội ngũ giàu kinh nghiệm trong tư vấn BIM, thiết kế, đào tạo và quản lý thi công. Chúng tôi kết nối năng lực chuyên môn với tư duy đổi mới để giải quyết những thách thức phức tạp của dự án.</p><div className="about-story-stats">{companyStats.map(item=><div key={item.label}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div><div className="overview-signature">BIM4C <span>One team · Great solution</span></div></div></section>
  <section className="about-timeline"><div className="page-shell"><header><p className="eyebrow">HÀNH TRÌNH PHÁT TRIỂN</p><h2>Từ nền tảng vững chắc đến tương lai số</h2></header><div className="timeline-track">{milestones.map((item,index)=><article key={item.year}><span>0{index+1}</span><strong>{item.year}</strong><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
  <section className="about-pillars"><div className="page-shell"><header className="about-section-head"><div><p className="eyebrow">ĐỊNH HƯỚNG PHÁT TRIỂN</p><h2>Một định hướng.<br/>Ba trụ cột dẫn đường.</h2></div><p>Những nguyên tắc thống nhất cách BIM4C suy nghĩ, hành động và tạo ra giá trị trong mỗi dự án.</p></header><div className="pillar-grid"><article><span>01</span><h3>Tầm nhìn</h3><p>Trở thành đơn vị tiên phong về giải pháp xây dựng số, tạo ra chuẩn mực mới về phối hợp và quản trị thông tin.</p></article><article><span>02</span><h3>Sứ mệnh</h3><p>Kết nối con người, quy trình và công nghệ để nâng cao chất lượng công trình và hiệu quả đầu tư.</p></article><article><span>03</span><h3>Giá trị cốt lõi</h3><p>Chính trực trong cam kết, chính xác trong chuyên môn và chủ động đổi mới trong mọi hoạt động.</p></article></div></div></section>
  <Leadership/><ContactBand/></main>}
