"use client";
import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";
import { adminMediaApi, type AdminMedia } from "@/features/admin/api/media";

export function MediaLibrary() {
  const [items, setItems] = useState<AdminMedia[]>([]); const [selected, setSelected] = useState<AdminMedia | null>(null); const [search, setSearch] = useState(""); const [feedback, setFeedback] = useState(""); const [busy, setBusy] = useState(false); const input = useRef<HTMLInputElement>(null);
  const load = useCallback(async () => { try { setItems((await adminMediaApi.list(search)).data); } catch (error) { setFeedback(error instanceof Error ? error.message : "Không thể tải media"); } }, [search]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  async function upload(file?: File) { if (!file || busy) return; setBusy(true); try { await adminMediaApi.upload(file, ""); setFeedback("Đã tải tệp lên."); await load(); } catch (error) { setFeedback(error instanceof Error ? error.message : "Không thể tải tệp"); } finally { setBusy(false); if (input.current) input.current.value = ""; } }
  async function saveAlt() { if (!selected || busy) return; setBusy(true); try { const result = await adminMediaApi.update(selected.id, selected.alt ?? ""); setSelected(result.data); await load(); setFeedback("Đã cập nhật mô tả ảnh."); } catch (error) { setFeedback(error instanceof Error ? error.message : "Không thể cập nhật"); } finally { setBusy(false); } }
  async function remove() { if (!selected || busy || !window.confirm(`Xóa “${selected.filename}”?`)) return; setBusy(true); try { await adminMediaApi.remove(selected.id); setSelected(null); await load(); } catch (error) { setFeedback(error instanceof Error ? error.message : "Không thể xóa"); } finally { setBusy(false); } }
  return <section className="admin-panel media-library">{feedback && <div className="homepage-feedback">{feedback}<button onClick={() => setFeedback("")}>×</button></div>}<div className="media-toolbar"><label><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Tìm kiếm tệp..."/></label><input ref={input} hidden type="file" accept="image/*" onChange={e => void upload(e.target.files?.[0])}/><button disabled={busy} onClick={() => input.current?.click()}>↑ {busy ? "Đang xử lý…" : "Tải tệp lên"}</button></div><div className="media-layout"><div className="media-grid">{items.map(item => <button className={selected?.id === item.id ? "active" : ""} onClick={() => setSelected(item)} key={item.id}><span><Image unoptimized src={item.url} alt={item.alt ?? ""} fill sizes="220px"/></span><strong>{item.filename}</strong><small>{item.mimeType} · {(item.size / 1024 / 1024).toFixed(1)} MB</small></button>)}</div>{selected && <aside className="media-inspector"><button onClick={() => setSelected(null)}>×</button><div><Image unoptimized src={selected.url} alt={selected.alt ?? ""} fill sizes="320px"/></div><h3>{selected.filename}</h3><dl><div><dt>Định dạng</dt><dd>{selected.mimeType}</dd></div><div><dt>Dung lượng</dt><dd>{(selected.size / 1024 / 1024).toFixed(2)} MB</dd></div><div><dt>Ngày tải lên</dt><dd>{new Intl.DateTimeFormat("vi-VN").format(new Date(selected.createdAt))}</dd></div></dl><label>Văn bản thay thế<input value={selected.alt ?? ""} onChange={e => setSelected({ ...selected, alt: e.target.value })}/></label><button disabled={busy} className="admin-primary" onClick={() => void saveAlt()}>Lưu mô tả</button><button disabled={busy} className="media-delete" onClick={() => void remove()}>Xóa khỏi thư viện</button></aside>}</div></section>;
}
