"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type User={id:string;email:string;name:string;status:"ACTIVE"|"DISABLED";roles:{role:string}[]};
async function api(path:string,init?:RequestInit){const r=await fetch(`/api/admin/users${path}`,{...init,headers:{"Content-Type":"application/json",...init?.headers}});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.message??"Yêu cầu thất bại");return b}
export function UsersManager(){
 const[items,setItems]=useState<User[]>([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[show,setShow]=useState(false);
 const load=useCallback(async()=>{try{setItems((await api(`?search=${encodeURIComponent(search)}`)).data)}catch(e){setError(e instanceof Error?e.message:"Không thể tải")}},[search]);
 useEffect(()=>{api(`?search=${encodeURIComponent(search)}`).then(x=>setItems(x.data)).catch(e=>setError(e instanceof Error?e.message:"Không thể tải"))},[search]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await api("",{method:"POST",body:JSON.stringify({name:f.get("name"),email:f.get("email"),password:f.get("password"),roles:[f.get("role")]})});setShow(false);await load()}catch(x){setError(x instanceof Error?x.message:"Không thể tạo")}finally{setBusy(false)}}
 async function status(u:User){setBusy(true);try{await api(`/${u.id}/status`,{method:"PATCH",body:JSON.stringify({status:u.status==="ACTIVE"?"DISABLED":"ACTIVE"})});await load()}catch(x){setError(x instanceof Error?x.message:"Không thể cập nhật")}finally{setBusy(false)}}
 return <section className="admin-panel content-panel"><div className="content-toolbar"><label><input placeholder="Tìm tên hoặc email" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="admin-primary" onClick={()=>setShow(!show)}>Tạo tài khoản</button></div>{show&&<form onSubmit={create} className="content-form"><input name="name" required minLength={2} placeholder="Họ tên"/><input name="email" required type="email" placeholder="Email"/><input name="password" required minLength={12} type="password" placeholder="Mật khẩu (ít nhất 12 ký tự)"/><select name="role"><option>EDITOR</option><option>ADMIN</option><option>SUPER_ADMIN</option></select><button disabled={busy} className="admin-primary">{busy?"Đang lưu…":"Lưu"}</button></form>}{error&&<p className="homepage-feedback">{error}</p>}<div className="admin-table-wrap"><table><thead><tr><th>NGƯỜI DÙNG</th><th>VAI TRÒ</th><th>TRẠNG THÁI</th><th/></tr></thead><tbody>{items.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td>{u.roles.map(x=>x.role).join(", ")}</td><td>{u.status}</td><td><button disabled={busy} onClick={()=>void status(u)}>{u.status==="ACTIVE"?"Vô hiệu hóa":"Kích hoạt"}</button></td></tr>)}</tbody></table></div></section>
}
