import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PageHero } from "@/components/shared/PageHero";
import { ROUTES } from "@/constants/routes";
import { getCourses } from "@/features/courses/api/queries";
export const metadata:Metadata={title:"Khóa học | BIM4C",description:"Chương trình đào tạo BIM thực chiến dành cho kỹ sư và doanh nghiệp."};
export default async function CoursesPage(){const courses=await getCourses();return <><PageHero eyebrow="BIM4C ACADEMY" title="Học từ dự án. Làm được việc." description="Chương trình BIM thực chiến được xây dựng từ kinh nghiệm triển khai và nhu cầu thật của doanh nghiệp." image="/images/service-training.jpg"/>
  <section className="bg-[#f5fafa] py-16 lg:py-24"><div className="mx-auto w-[calc(100%_-_32px)] max-w-[1440px] md:w-[calc(100%_-_48px)] lg:w-[calc(100%_-_80px)]"><header className="mb-9"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-[#087f7d]">LỘ TRÌNH ĐÀO TẠO</p><h2 className="text-section-title font-semibold text-[#063f46]">Chọn điểm bắt đầu phù hợp</h2></header><div className="grid gap-6">{courses.map((course,index)=><article className="group relative grid overflow-hidden bg-white md:grid-cols-[minmax(300px,38%)_1fr]" key={course.slug}><Link className="absolute inset-0 z-10" href={ROUTES.courseDetail(course.slug)} aria-label={`Xem ${course.title}`}/><div className="relative min-h-[260px] overflow-hidden md:min-h-[360px]"><Image className="object-cover transition-transform duration-500 group-hover:scale-105" src={course.image} alt={course.title} fill sizes="(max-width: 767px) 100vw, 38vw"/><span className="absolute left-5 top-5 grid size-11 place-items-center bg-[#063f46] text-xs font-semibold text-white">0{index+1}</span></div><div className="p-6 md:p-10"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-[#087f7d]">{course.eyebrow}</p><h3 className="text-subtitle font-semibold text-[#063f46]">{course.title}</h3><p className="mt-4 leading-relaxed text-[#667775]">{course.description}</p><ul className="my-6 border-t border-[#dbe7e5]">{course.highlights.map(item=><li className="border-b border-[#dbe7e5] py-3 text-sm text-[#667775]" key={item}>{item}</li>)}</ul><span className="text-xs font-semibold uppercase text-[#087f7d]">Xem chương trình →</span></div></article>)}</div></div></section>
  <section className="bg-[#063f46] py-16 text-white lg:py-24"><div className="mx-auto w-[calc(100%_-_32px)] max-w-[1440px] md:w-[calc(100%_-_48px)] lg:w-[calc(100%_-_80px)]"><header className="mb-9"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-[#ffffff]">HỌC ĐỂ LÀM ĐƯỢC</p><h2 className="text-section-title font-semibold">Trải nghiệm đào tạo khác biệt</h2></header><div className="grid grid-cols-1 border-l border-t border-white/20 md:grid-cols-3"><article className="min-h-64 border-b border-r border-white/20 p-7"><span className="text-xs font-semibold text-[#ffffff]">01</span><h3 className="mb-3 mt-12 text-xl font-semibold">Tình huống thực tế</h3><p className="text-sm leading-relaxed text-white/65">Học từ dữ liệu, mô hình và vấn đề đã xuất hiện trong dự án xây dựng.</p></article><article className="min-h-64 border-b border-r border-white/20 p-7"><span className="text-xs font-semibold text-[#ffffff]">02</span><h3 className="mb-3 mt-12 text-xl font-semibold">Mentor đồng hành</h3><p className="text-sm leading-relaxed text-white/65">Nhận phản hồi trực tiếp để hiểu đúng và cải thiện sau mỗi bài thực hành.</p></article><article className="min-h-64 border-b border-r border-white/20 p-7"><span className="text-xs font-semibold text-[#ffffff]">03</span><h3 className="mb-3 mt-12 text-xl font-semibold">Năng lực đầu ra</h3><p className="text-sm leading-relaxed text-white/65">Hoàn thành sản phẩm cuối khóa có thể sử dụng trong hồ sơ nghề nghiệp.</p></article></div></div></section></>}
