"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { EmptyState } from "@/components/ui/EmptyState";
import { ROUTES } from "@/constants/routes";
import { ALL_PROJECT_FILTER, PROJECT_CATEGORIES, PROJECT_PAGE_SIZE } from "@/features/projects/constants";
import { filterProjects } from "@/features/projects/selectors/filter-projects";
import type { Project } from "@/features/projects/types/project";

const fieldClass = "min-w-0 bg-white px-[18px] py-[15px]";
const controlClass = "h-[38px] w-full border-0 bg-white p-0 text-sm text-[#163b3a] outline-none focus:shadow-[inset_0_-2px_#09a7a5]";

export function ProjectExplorer({ projects }: { projects: Project[] }) {
  const [category, setCategory] = useState(ALL_PROJECT_FILTER), [query, setQuery] = useState(""), [location, setLocation] = useState(ALL_PROJECT_FILTER), [year, setYear] = useState(ALL_PROJECT_FILTER), [status, setStatus] = useState(ALL_PROJECT_FILTER), [page, setPage] = useState(1);
  const update = (setter: (value: string) => void, value: string) => { setter(value); setPage(1); };
  const filtered = useMemo(() => filterProjects(projects, { category, search: query, location, year, status }), [projects, category, query, location, year, status]);
  const pages = Math.max(1, Math.ceil(filtered.length / PROJECT_PAGE_SIZE));
  const visible = filtered.slice((page - 1) * PROJECT_PAGE_SIZE, page * PROJECT_PAGE_SIZE);
  const reset = () => { setCategory(ALL_PROJECT_FILTER); setQuery(""); setLocation(ALL_PROJECT_FILTER); setYear(ALL_PROJECT_FILTER); setStatus(ALL_PROJECT_FILTER); setPage(1); };

  return <section className="w-full bg-[#f5fafa] py-14 lg:py-24"><div className="mx-auto w-[calc(100%_-_32px)] max-w-[1440px] md:w-[calc(100%_-_48px)] lg:w-[calc(100%_-_80px)]">
    <div className="mb-[26px] flex overflow-x-auto border-b border-[#dbe7e5] md:mb-9" role="tablist" aria-label="Loại dự án">{PROJECT_CATEGORIES.map((item) => <button type="button" role="tab" aria-selected={category === item} className={`min-h-[52px] flex-none border-b-[3px] px-[15px] text-[16px] font-semibold md:px-[22px] ${category === item ? "border-[#09a7a5] text-[#087f7d]" : "border-transparent text-[#667775]"}`} onClick={() => update(setCategory, item)} key={item}>{item}</button>)}</div>
    <div className="mb-5 grid grid-cols-1 gap-px border border-[#dbe7e5] bg-[#dbe7e5] md:grid-cols-2 xl:grid-cols-[2fr_1fr_1fr_1fr]"><label className={fieldClass}><span className="mb-[7px] block text-xs font-semibold uppercase tracking-[.06em] text-[#063f46]">Tên dự án</span><input className={controlClass} value={query} onChange={(event) => update(setQuery, event.target.value)} type="search" placeholder="Tìm kiếm..." /></label><FilterSelect label="Vị trí" value={location} values={[...new Set(projects.map((item) => item.location))]} onChange={(value) => update(setLocation, value)} /><FilterSelect label="Thời gian" value={year} values={[...new Set(projects.map((item) => item.year))]} onChange={(value) => update(setYear, value)} /><FilterSelect label="Tiến độ" value={status} values={[...new Set(projects.map((item) => item.status))]} onChange={(value) => update(setStatus, value)} /></div>
    <div className="mb-6 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><p className="m-0 text-label text-[#667775]"><strong className="text-xl text-[#063f46]">{filtered.length}</strong> dự án phù hợp</p><button className="self-start whitespace-nowrap text-xs font-semibold uppercase text-[#087f7d] sm:self-auto" type="button" onClick={reset}>Đặt lại bộ lọc</button></div>
    <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">{visible.map((project, index) => <article className="group relative aspect-[4/5] overflow-hidden bg-[#063f46] shadow-sm" key={project.slug}><Link className="absolute inset-0 z-10 focus-visible:outline-2 focus-visible:outline-offset-[-3px] focus-visible:outline-white" href={ROUTES.projectDetail(project.slug)} aria-label={`Xem ${project.title}`} /><Image className="object-cover transition-transform duration-700 ease-out group-hover:scale-105 group-focus-within:scale-105" src={project.image} alt={project.title} fill sizes="(max-width: 767px) 100vw, (max-width: 1279px) 50vw, 33vw" /><div className="absolute inset-0 bg-gradient-to-t from-[#063f46]/95 via-[#063f46]/20 to-transparent transition-colors duration-500 group-hover:from-[#063f46] group-hover:via-[#063f46]/45 group-focus-within:from-[#063f46] group-focus-within:via-[#063f46]/45" /><span className="absolute left-5 top-5 grid size-12 place-items-center bg-[#063f46]/90 text-xs font-semibold text-white">{String((page - 1) * PROJECT_PAGE_SIZE + index + 1).padStart(2, "0")}</span><div className="absolute inset-x-0 bottom-0 p-6 text-white"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-[#ffffff]">{project.category}</p><h2 className="text-subtitle font-semibold leading-tight">{project.title}</h2><dl className="mt-4 grid overflow-hidden text-xs transition-[max-height,opacity] duration-500 ease-out lg:max-h-0 lg:opacity-0 lg:group-hover:max-h-56 lg:group-hover:opacity-100 lg:group-focus-within:max-h-56 lg:group-focus-within:opacity-100"><div className="grid grid-cols-[68px_1fr] gap-2 border-t border-white/25 py-2"><dt className="font-semibold uppercase text-white/60">Năm</dt><dd>{project.year}</dd></div><div className="grid grid-cols-[68px_1fr] gap-2 border-t border-white/25 py-2"><dt className="font-semibold uppercase text-white/60">Vị trí</dt><dd className="line-clamp-2">{project.location}</dd></div><div className="grid grid-cols-[68px_1fr] gap-2 border-t border-white/25 py-2"><dt className="font-semibold uppercase text-white/60">Quy mô</dt><dd className="line-clamp-2">{project.scale ?? "Đang cập nhật"}</dd></div><div className="grid grid-cols-[68px_1fr] gap-2 border-t border-white/25 py-2"><dt className="font-semibold uppercase text-white/60">Tiến độ</dt><dd>{project.status}</dd></div></dl><span className="mt-4 inline-flex text-xs font-semibold uppercase text-white">Xem dự án <b className="ml-2 transition-transform group-hover:translate-x-1">→</b></span></div></article>)}{visible.length === 0 && <EmptyState title="Không tìm thấy dự án" description="Hãy thử thay đổi hoặc đặt lại bộ lọc." />}</div>
    {pages > 1 && <Pagination page={page} pages={pages} onChange={setPage} />}
  </div></section>;
}

function FilterSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className={fieldClass}><span className="mb-[7px] block text-xs font-semibold uppercase tracking-[.06em] text-[#063f46]">{label}</span><select className={controlClass} value={value} onChange={(event) => onChange(event.target.value)}><option>Tất cả</option>{values.map((item) => <option key={item}>{item}</option>)}</select></label>; }

function Pagination({ page, pages, onChange }: { page: number; pages: number; onChange: (page: number) => void }) { const button = "size-[42px] border border-[#dbe7e5] text-xs font-semibold md:size-[46px]"; return <nav className="mt-[42px] flex justify-center gap-2" aria-label="Phân trang"><button className={`${button} disabled:cursor-not-allowed disabled:opacity-35`} type="button" disabled={page === 1} onClick={() => onChange(page - 1)}>←</button>{Array.from({ length: pages }, (_, index) => index + 1).map((number) => <button type="button" className={`${button} ${page === number ? "border-[#087f7d] bg-[#087f7d] text-white" : "bg-white text-[#087f7d]"}`} aria-current={page === number ? "page" : undefined} onClick={() => onChange(number)} key={number}>{String(number).padStart(2, "0")}</button>)}<button className={`${button} disabled:cursor-not-allowed disabled:opacity-35`} type="button" disabled={page === pages} onClick={() => onChange(page + 1)}>→</button></nav>; }
